name: Crear discusión con resumen de los ultimos 5 commits

on:
  workflow_dispatch:

jobs:
  crear-discusion:
    runs-on: ubuntu-latest
    env: 
      SUMMARY_FILE : ${{ vars.SUMMARY_FILE }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Obtener últimos 5 commits y guardar como Markdown
        id: get_commits
        run: |
          echo "# Últimos 5 commits de la rama main" > $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          git fetch origin main
          git log origin/main -n 5 --pretty=format:"- %h %s (%an, %ad)" --date=short >> $SUMMARY_FILE
          echo $SUMMARY_FILE

      - name: Obtener repositoryId con GraphQL
        id: get_repo_id
        env:
          GH_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        run: |
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)

          QUERY=$(cat <<EOF
          {
            "query": "query { repository(owner: \\"$REPO_OWNER\\", name: \\"$REPO_NAME\\") { id } }"
          } 
          EOF
          )

          REPO_ID=$(curl -s -H "Authorization: bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$QUERY" \
            https://api.github.com/graphql | jq -r '.data.repository.id')

          echo "repository_id=$REPO_ID" >> $GITHUB_OUTPUT

      - name: Obtener fecha y hora actual
        id: get_datetime
        run: echo "now=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Crear discusión con resumen de commits
        id: create-discussion
        uses: abirismyname/create-discussion@main   
        with:
          title: "Resumen de commits - ${{ steps.get_datetime.outputs.now }}"
          body-filepath: ${{ env.SUMMARY_FILE }}
          repository-id: ${{ steps.get_repo_id.outputs.repository_id }}
          category-id: ${{ secrets.DISCUSSION_CATEGORY_ID }}
          github-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
  
      - name: Imprimir ID y URL de Discusion
        run: |
          echo discussion-id: ${{steps.create-discussion.outputs.discussion-id}} 
          echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}
